### ISSUE TITLE
[FEATURE] - Add the support for multiple DT on the same WLDT Instance

### ISSUE THREAD

**Issue by piconem** [wldt/wldt-core-java#13]
The idea is that the library can support also a working mode where multiple DTs can be instantiated on the same WLDT Engine in a way that we do not need to have multiple independent processes if it is not strictly needed.

This change should be easily introduced but the main "issue" is the fact that the EventBus is a Singleton that a the moment do not handle and target a specific event to the target DT.

Main Required changes to support the feature are:

- Update the Event Bus introducing the reference to the target DT involved, allowing the EventBus to support multiple messages with different DT active at the same time
- Test the Event Bus
- Update implementation to add the correct WLDT Event DT reference in every communication 
- Test It
- Update/Refactor classes allowing a scenario like the following: 

```java
DigitalTwin dt1 = new DigitalTwin("dt1", shadowingFunction1);
dt1.addPhysicalAdatper(...)
dt1.addDigitalAdapter(...)

DigitalTwin dt2 = new DigitalTwin("dt2", shadowingFunction1);
dt2.addPhysicalAdatper(...)
dt2.addDigitalAdapter(...)

DigitalTwinEngine dtEngine = new DigitalTwinEngine();
dtEngine.start(dt1, dt2, ....)
```

**Comment by samubura** [comment]
Addressed in #16
